services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nasa-explorer-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - nasa-explorer-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: nasa-explorer-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --port 5173 --host 0.0.0.0
    networks:
      - nasa-explorer-net

networks:
  nasa-explorer-net:
    driver: bridge
