version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/docker/Dockerfile.backend
    container_name: nasa-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/Dockerfile.frontend
    container_name: nasa-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  redis:
    image: redis:6
    container_name: nasa-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5