# === Frontend Dockerfile ===
FROM node:20-alpine AS base

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# Development
FROM base AS dev
CMD ["npm", "run", "dev", "--", "--host"]

# Production
FROM base AS prod
ENV NODE_ENV=production
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "preview", "--", "--host"]